name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_gemini: ^2.0.5
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  record: ^5.0.0  
  http: ^1.2.2
  google_generative_ai: ^0.4.4
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
